### PR TITLE
Add simplifyFactor to esri-feature layer

### PR DESCRIPTION
**Pull request by michaelpnelson**
This allows SMK configuration to specify a "simplifyFactor" value to increase performance for layers with many complex features.

### CODE REVIEW

**Comment by michaelpnelson** [comment]
Usage example: https://developers.arcgis.com/esri-leaflet/samples/simplifying-complex-features/

**Review by dgboss — APPROVED** [review]
Looks good, might want to update documentation though.

**Comment by michaelpnelson** [comment]
> Looks good, might want to update documentation though.

Thanks for reminding me about documentation :) I'll push another commit with a doc update.

**Comment by michaelpnelson** [comment]
> > Looks good, might want to update documentation though.
> 
> Thanks for reminding me about documentation :) I'll push another commit with a doc update.

Ah, and now I remember that there IS no documentation for the "esri-feature" layer. I have an old backlog item for this.

**Pull request merged**
